# Generated by Django 5.0.11 on 2025-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur')], default='user', max_length=10),
        ),
    ]
