# Generated by Django 5.0.11 on 2025-03-26 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone n'est pas valide.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
    ]
